# Generated by Django 2.2.4 on 2019-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
